"""
agents/niche_profiles.py
─────────────────────────
Complete industry/niche profile library.
Each profile defines everything the bot needs to produce
the best possible content for that industry — zero manual config.
"""

NICHE_PROFILES = {

    "technology": {
        "id":            "technology",
        "label":         "Technology & AI",
        "emoji":         "⚡",
        "description":   "AI, gadgets, software, future tech, cybersecurity, startups",
        "audience":      "curious people aged 18–40 interested in tech and the future",
        "tone":          "energetic, slightly mind-blowing, uses simple analogies",
        "upload_hour":   10,
        "video_formats": ["explainer", "list", "documentary"],
        "best_hooks":    ["shocking_stat", "counter_intuitive", "bold_claim"],
        "voice_en":      "en-US-GuyNeural",
        "voice_hi":      "hi-IN-MadhurNeural",
        "music_mood":    "cinematic electronic ambient",
        "thumbnail_style": "dark blue/cyan, tech imagery, circuit boards, AI visuals",
        "keywords_seed": ["artificial intelligence", "technology 2025", "future tech",
                          "AI tools", "gadgets", "cybersecurity", "startup"],
        "news_queries":  ["artificial intelligence", "technology", "AI", "robotics",
                          "cybersecurity", "machine learning", "startup"],
        "hn_keywords":   ["AI", "machine learning", "startup", "open source",
                          "programming", "software", "hardware", "robotics"],
        "wiki_topics":   ["Artificial_intelligence", "Technology"],
        "yt_category":   "28",
        "color_accent":  "#00D4FF",
    },

    "finance": {
        "id":            "finance",
        "label":         "Finance & Money",
        "emoji":         "💰",
        "description":   "Investing, stocks, crypto, passive income, wealth building",
        "audience":      "young professionals aged 22–45 wanting financial freedom",
        "tone":          "authoritative but accessible, uses real numbers and stories",
        "upload_hour":   8,
        "video_formats": ["explainer", "list", "story"],
        "best_hooks":    ["shocking_stat", "bold_claim", "question"],
        "voice_en":      "en-US-GuyNeural",
        "voice_hi":      "hi-IN-MadhurNeural",
        "music_mood":    "corporate background professional",
        "thumbnail_style": "dark green/gold, money imagery, charts going up, wealth symbols",
        "keywords_seed": ["investing", "stock market", "passive income", "financial freedom",
                          "how to make money", "wealth", "savings", "crypto"],
        "news_queries":  ["stock market", "investing", "cryptocurrency", "economy",
                          "financial news", "interest rates", "inflation"],
        "hn_keywords":   ["investing", "finance", "startup funding", "IPO", "economics"],
        "wiki_topics":   ["Investment", "Personal_finance"],
        "yt_category":   "25",
        "color_accent":  "#00FF88",
    },

    "history": {
        "id":            "history",
        "label":         "History & Civilisation",
        "emoji":         "🏛️",
        "description":   "Ancient civilisations, wars, forgotten stories, historical mysteries",
        "audience":      "curious adults aged 25–55 who love learning and storytelling",
        "tone":          "dramatic, documentary-style, makes the past feel urgent and alive",
        "upload_hour":   14,
        "video_formats": ["documentary", "story", "explainer"],
        "best_hooks":    ["story_open", "shocking_stat", "counter_intuitive"],
        "voice_en":      "en-GB-RyanNeural",
        "voice_hi":      "hi-IN-MadhurNeural",
        "music_mood":    "epic orchestral documentary",
        "thumbnail_style": "dark amber/gold, ancient ruins, dramatic sky, historical art",
        "keywords_seed": ["ancient history", "mysteries of history", "lost civilisation",
                          "world war", "empire", "historical facts", "archaeology"],
        "news_queries":  ["history discovery", "archaeology", "ancient civilisation",
                          "historical mystery"],
        "hn_keywords":   ["history", "archaeology", "ancient"],
        "wiki_topics":   ["History", "Ancient_history", "World_War_II"],
        "yt_category":   "27",
        "color_accent":  "#FFB800",
    },

    "science": {
        "id":            "science",
        "label":         "Science & Universe",
        "emoji":         "🔬",
        "description":   "Space, physics, biology, psychology, new discoveries",
        "audience":      "intellectually curious people aged 16–50",
        "tone":          "awe-inspiring, mind-expanding, makes complexity simple",
        "upload_hour":   11,
        "video_formats": ["explainer", "documentary", "list"],
        "best_hooks":    ["counter_intuitive", "shocking_stat", "bold_claim"],
        "voice_en":      "en-US-GuyNeural",
        "voice_hi":      "hi-IN-MadhurNeural",
        "music_mood":    "ambient space cinematic",
        "thumbnail_style": "deep space purple/blue, planets, microscopic views, glowing effects",
        "keywords_seed": ["space exploration", "physics explained", "science facts",
                          "human biology", "psychology", "universe", "quantum"],
        "news_queries":  ["science discovery", "space exploration", "NASA", "physics",
                          "biology research", "new discovery"],
        "hn_keywords":   ["science", "space", "physics", "biology", "research", "NASA"],
        "wiki_topics":   ["Science", "Astronomy", "Physics"],
        "yt_category":   "28",
        "color_accent":  "#BB00FF",
    },

    "motivation": {
        "id":            "motivation",
        "label":         "Motivation & Success",
        "emoji":         "🚀",
        "description":   "Success stories, habits, mindset, productivity, life advice",
        "audience":      "ambitious people aged 18–40 wanting to improve their life",
        "tone":          "high-energy, personal, uses powerful stories and emotional peaks",
        "upload_hour":   6,
        "video_formats": ["story", "list", "explainer"],
        "best_hooks":    ["story_open", "bold_claim", "question"],
        "voice_en":      "en-US-GuyNeural",
        "voice_hi":      "hi-IN-MadhurNeural",
        "music_mood":    "inspiring uplifting motivational",
        "thumbnail_style": "orange/gold sunrise, person achieving, bold typography",
        "keywords_seed": ["success habits", "billionaire mindset", "how to be successful",
                          "morning routine", "motivation", "self improvement", "discipline"],
        "news_queries":  ["success story", "entrepreneur", "motivation", "productivity",
                          "self improvement"],
        "hn_keywords":   ["productivity", "self-improvement", "entrepreneurship", "habits"],
        "wiki_topics":   ["Motivation", "Success"],
        "yt_category":   "22",
        "color_accent":  "#FF8C00",
    },

    "business": {
        "id":            "business",
        "label":         "Business & Entrepreneurship",
        "emoji":         "💼",
        "description":   "Business stories, case studies, entrepreneurship, marketing secrets",
        "audience":      "entrepreneurs and aspiring business owners aged 22–50",
        "tone":          "analytical yet engaging, uses real business data and case studies",
        "upload_hour":   9,
        "video_formats": ["story", "documentary", "explainer"],
        "best_hooks":    ["story_open", "shocking_stat", "bold_claim"],
        "voice_en":      "en-US-GuyNeural",
        "voice_hi":      "hi-IN-MadhurNeural",
        "music_mood":    "corporate success background",
        "thumbnail_style": "dark blue/gold, corporate imagery, success symbols, money",
        "keywords_seed": ["business case study", "startup story", "how company grew",
                          "entrepreneur secrets", "business strategy", "marketing"],
        "news_queries":  ["business strategy", "startup success", "company story",
                          "entrepreneur", "marketing strategy"],
        "hn_keywords":   ["startup", "business", "entrepreneurship", "marketing", "SaaS"],
        "wiki_topics":   ["Entrepreneurship", "Business"],
        "yt_category":   "25",
        "color_accent":  "#FFD700",
    },

    "health": {
        "id":            "health",
        "label":         "Health & Wellness",
        "emoji":         "💪",
        "description":   "Nutrition, fitness, longevity, mental health, sleep science",
        "audience":      "health-conscious adults aged 20–55",
        "tone":          "trustworthy, science-backed, practical and actionable",
        "upload_hour":   7,
        "video_formats": ["explainer", "list", "documentary"],
        "best_hooks":    ["shocking_stat", "counter_intuitive", "question"],
        "voice_en":      "en-US-JennyNeural",
        "voice_hi":      "hi-IN-SwaraNeural",
        "music_mood":    "calm wellness nature background",
        "thumbnail_style": "clean green/white, healthy food, fit body, natural imagery",
        "keywords_seed": ["health tips", "nutrition facts", "fitness science", "longevity",
                          "sleep science", "mental health", "diet facts"],
        "news_queries":  ["health research", "nutrition study", "fitness science",
                          "mental health", "longevity research"],
        "hn_keywords":   ["health", "nutrition", "fitness", "longevity", "sleep"],
        "wiki_topics":   ["Health", "Nutrition", "Physical_fitness"],
        "yt_category":   "26",
        "color_accent":  "#44FF88",
    },

    "gaming": {
        "id":            "gaming",
        "label":         "Gaming & Esports",
        "emoji":         "🎮",
        "description":   "Game reviews, gaming news, industry history, esports stories",
        "audience":      "gamers aged 14–35",
        "tone":          "enthusiastic, fast-paced, uses gaming culture references",
        "upload_hour":   16,
        "video_formats": ["list", "story", "documentary"],
        "best_hooks":    ["shocking_stat", "story_open", "bold_claim"],
        "voice_en":      "en-US-GuyNeural",
        "voice_hi":      "hi-IN-MadhurNeural",
        "music_mood":    "electronic gaming energetic",
        "thumbnail_style": "neon red/purple, game characters, dramatic action shots",
        "keywords_seed": ["gaming facts", "video game history", "esports", "game review",
                          "gaming industry", "best games ever"],
        "news_queries":  ["gaming news", "video game release", "esports", "game industry"],
        "hn_keywords":   ["gaming", "game development", "esports", "Unity", "Unreal"],
        "wiki_topics":   ["Video_games", "Esports"],
        "yt_category":   "20",
        "color_accent":  "#FF4488",
    },

    "documentary": {
        "id":            "documentary",
        "label":         "Documentaries & True Stories",
        "emoji":         "🎬",
        "description":   "True crime, real events, investigative stories, human drama",
        "audience":      "adults aged 25–60 who love deep dives and true stories",
        "tone":          "gripping, investigative, builds suspense and delivers payoff",
        "upload_hour":   20,
        "video_formats": ["documentary", "story"],
        "best_hooks":    ["story_open", "shocking_stat", "question"],
        "voice_en":      "en-GB-RyanNeural",
        "voice_hi":      "hi-IN-MadhurNeural",
        "music_mood":    "mystery suspense documentary",
        "thumbnail_style": "dark dramatic, high contrast, faces, mystery vibes",
        "keywords_seed": ["true story", "documentary", "what really happened", "exposed",
                          "untold story", "real events", "investigation"],
        "news_queries":  ["documentary", "true crime", "investigation", "exposé",
                          "shocking story"],
        "hn_keywords":   ["investigation", "documentary", "crime", "corruption"],
        "wiki_topics":   ["Documentary_film", "True_crime"],
        "yt_category":   "27",
        "color_accent":  "#CC88FF",
    },

    "india": {
        "id":            "india",
        "label":         "India — Hindi Content 🇮🇳",
        "emoji":         "🇮🇳",
        "description":   "Indian business stories, Bollywood, cricket, Indian history, desi motivation",
        "audience":      "Hindi-speaking Indian audience aged 18–45",
        "tone":          "conversational Hindi, mixes English naturally, desi storytelling style",
        "upload_hour":   9,
        "video_formats": ["story", "documentary", "list"],
        "best_hooks":    ["story_open", "shocking_stat", "bold_claim"],
        "voice_en":      "en-IN-PrabhatNeural",
        "voice_hi":      "hi-IN-MadhurNeural",
        "music_mood":    "Bollywood instrumental background",
        "thumbnail_style": "vibrant Indian colours, bold Hindi/English text mix, Bollywood style",
        "keywords_seed": ["भारत", "India business story", "Indian startup", "Bollywood",
                          "cricket", "Indian history", "success story India"],
        "news_queries":  ["India news", "Indian startup", "Bollywood", "IPL cricket",
                          "India economy", "Indian business"],
        "hn_keywords":   ["India", "Indian startup", "Flipkart", "Tata", "Reliance"],
        "wiki_topics":   ["India", "History_of_India"],
        "yt_category":   "22",
        "color_accent":  "#FF9933",
        "force_language": "hi",
    },
}

def get_profile(niche_id: str) -> dict:
    """Return niche profile, falling back to technology."""
    return NICHE_PROFILES.get(niche_id, NICHE_PROFILES["technology"])

def all_niches() -> list[dict]:
    """Return list of all profiles (for dashboard selector)."""
    return list(NICHE_PROFILES.values())
